// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SQ-Jeepify-Monitor-All

#ifndef _SQ_JEEPIFY_MONITOR_ALL_UI_H
#define _SQ_JEEPIFY_MONITOR_ALL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_ScrMenu.h"
#include "screens/ui_ScrSettings.h"
#include "screens/ui_ScrPeers.h"
#include "screens/ui_ScrJSON.h"
#include "screens/ui_ScrPeer.h"
#include "screens/ui_ScrEichen.h"
#include "screens/ui_ScrVolt.h"
#include "screens/ui_ScrPeriph.h"
#include "screens/ui_ScrMulti.h"
#include "screens/ui_ScrSystem.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_jeepifybackground_png);    // assets/JeepifyBackground.png
LV_IMG_DECLARE(ui_img_rubicon_png);    // assets/Rubicon.png
LV_IMG_DECLARE(ui_img_menubtn1_png);    // assets/MenuBtn1.png
LV_IMG_DECLARE(ui_img_menubtn2_png);    // assets/MenuBtn2.png
LV_IMG_DECLARE(ui_img_menubtn3_png);    // assets/MenuBtn3.png
LV_IMG_DECLARE(ui_img_menubtn4_png);    // assets/MenuBtn4.png
LV_IMG_DECLARE(ui_img_ansgarmodule_4_png);    // assets/AnsgarModule_4.png
LV_IMG_DECLARE(ui_img_friedermodule_disp_png);    // assets/FriederModule_Disp.png
LV_IMG_DECLARE(ui_img_horstrelais2_png);    // assets/HorstRelais2.png
LV_IMG_DECLARE(ui_img_1769637049);    // assets/PeterRelais-1.png
LV_IMG_DECLARE(ui_img_rolfmodule_round_png);    // assets/RolfModule_round.png
LV_IMG_DECLARE(ui_img_888658411);    // assets/kipp-1-on-70.png
LV_IMG_DECLARE(ui_img_1528892059);    // assets/kipp-1-neutral-120.png
LV_IMG_DECLARE(ui_img_1471590615);    // assets/kipp-1-neutral-45.png
LV_IMG_DECLARE(ui_img_743505413);    // assets/kipp-1-neutral-70.png
LV_IMG_DECLARE(ui_img_1134846501);    // assets/kipp-1-off-120.png
LV_IMG_DECLARE(ui_img_237434643);    // assets/kipp-1-off-45.png
LV_IMG_DECLARE(ui_img_1640860301);    // assets/kipp-1-off-70.png
LV_IMG_DECLARE(ui_img_715952573);    // assets/kipp-1-on-120.png
LV_IMG_DECLARE(ui_img_434995191);    // assets/kipp-1-on-45.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
