// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SQ-Jeepify-Monitor360

#ifndef _UI_COMP_BUTTONSENSORSMALL_H
#define _UI_COMP_BUTTONSENSORSMALL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ButtonSensorSmall
#define UI_COMP_BUTTONSENSORSMALL_BUTTONSENSORSMALL 0
#define UI_COMP_BUTTONSENSORSMALL_LBLSENSSMALLPEER 1
#define UI_COMP_BUTTONSENSORSMALL_LBLSENSSMALLPERIPH 2
#define UI_COMP_BUTTONSENSORSMALL_LBLSENSSMALLVALUE 3
#define UI_COMP_BUTTONSENSORSMALL_LBLSENSPOS 4
#define UI_COMP_BUTTONSENSORSMALL_ARC2 5
#define _UI_COMP_BUTTONSENSORSMALL_NUM 6
lv_obj_t * ui_ButtonSensorSmall_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
