; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:DEV_360_KNOB]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
framework = arduino
board = ESP-LCD
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = huge_app.csv
build_flags = 
	-DDEV_360_KNOB=1
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
	https://github.com/lvgl/lvgl.git#release/v8.4
    https://github.com/esp-arduino-libs/ESP32_Display_Panel.git
    https://github.com/esp-arduino-libs/ESP32_IO_Expander.git
    https://github.com/esp-arduino-libs/esp-lib-utils.git
	bblanchon/ArduinoJson@^7.0.3
	mathieucarbou/ESPAsyncWebServer@^3.3.17	
build_src_filter = 
	+<*>
	-<Ui_*/>
	+<Ui_All/>
	-<Dev_*.*>
	-<Devices\>
	+<Dev_360_knob*.*>

[env:DEV_466_ALL]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
platform_packages = 
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = huge_app.csv
build_flags = 
	-DDEV_466_RED=1
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
	https://github.com/lvgl/lvgl.git#release/v8.4
    https://github.com/esp-arduino-libs/ESP32_Display_Panel.git
    https://github.com/esp-arduino-libs/ESP32_IO_Expander.git
    https://github.com/esp-arduino-libs/esp-lib-utils.git
	bblanchon/ArduinoJson@^7.0.3
	mathieucarbou/ESPAsyncWebServer@^3.3.17
build_src_filter = 
	+<*>
	-<Ui_*/>
	+<Ui_All/>
	-<Dev_*.*>
	-<Devices\>
	+<Dev_466_red*.*>

[env:ESP-360-SILVER]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = ESP-LCD
framework = arduino
platform_packages = 
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = huge_app.csv
build_flags = 
	-DDEV_360_SILVER=1
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
	;symlink://PlatformIO/Jeepify_Monitor_WSL/src/Devices/src/Devices/Dev_360_silver/lib/
	;symlink://src/Devices/Dev_360_silver/lib//ESP32_Display_Panel/
	;symlink://src/Devices/Dev_360_silver/lib//ESP32_IO_Expander/
	;symlink://src/Devices/Dev_360_silver/lib//lvgl/
	
	https://github.com/lvgl/lvgl.git#release/v8.4
	https://github.com/esp-arduino-libs/ESP32_Display_Panel#v0.1.4
    https://github.com/esp-arduino-libs/ESP32_IO_Expander.git#v0.0.2
    https://github.com/esp-arduino-libs/esp-lib-utils.git
	bblanchon/ArduinoJson@^7.0.3
	mathieucarbou/ESPAsyncWebServer@^3.3.17	
lib_extra_dirs =
    ;Devices/Dev_360_silver/lib/
	;\\wsl.localhost\Ubuntu\home\micha\PlatformIO\Jeepify_Monitor_WSL\src\Devices\Dev_360_silver\lib
build_src_filter = 
	+<*>
	-<Ui_*/>
	+<Ui_All/>
	-<Dev_*.*>
	-<Devices\>
	+<Dev_360_silver*.*>
;lib_ldf_mode = deep

[env:ESP-466-RED]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
platform_packages = 
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = huge_app.csv
build_flags = 
	-DDEV_466_RED=1
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
	https://github.com/lvgl/lvgl.git#release/v8.4
    https://github.com/esp-arduino-libs/ESP32_Display_Panel.git
    https://github.com/esp-arduino-libs/ESP32_IO_Expander.git
    https://github.com/esp-arduino-libs/esp-lib-utils.git
	bblanchon/ArduinoJson@^7.0.3
	mathieucarbou/ESPAsyncWebServer@^3.3.17
build_src_filter = 
	+<*>
	-<Ui_*/>
	+<Ui_All/>
	-<Dev_*.*>
	-<Devices\>
	+<Dev_466_red*.*>

[env:ESP-LCDMonitor_Knob]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
framework = arduino
board = ESP-LCD
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = huge_app.csv
build_flags = 
	-DDEV_360_KNOB=1
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
	https://github.com/lvgl/lvgl.git#release/v8.4
    https://github.com/esp-arduino-libs/ESP32_Display_Panel.git
    https://github.com/esp-arduino-libs/ESP32_IO_Expander.git
    https://github.com/esp-arduino-libs/esp-lib-utils.git
	bblanchon/ArduinoJson@^7.0.3
	mathieucarbou/ESPAsyncWebServer@^3.3.17	
build_src_filter = 
	+<*>
	-<Ui_*/>
	+<Ui_All/>
	-<Dev_*.*>
	-<Devices\>
	+<Dev_360_knob*.*>

[env:DEV_240_KLEIN]		
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = esp32-c3-devkitm-1
framework = arduino
platform_packages = 
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = huge_app.csv
build_flags = 
	-DDEV_240_KLEIN=1
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 
	https://github.com/lvgl/lvgl.git#release/v8.4
    https://github.com/esp-arduino-libs/ESP32_Display_Panel.git
    https://github.com/esp-arduino-libs/ESP32_IO_Expander.git
    https://github.com/esp-arduino-libs/esp-lib-utils.git
	bblanchon/ArduinoJson@^7.0.3
	mathieucarbou/ESPAsyncWebServer@^3.3.17
build_src_filter = 
	+<*>
	-<Ui_*/>
	-<*.html>
	+<Ui_All/>
	-<Dev_*.*>
	-<Devices\>
	+<Dev_240_klein*.*>
