// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SQ-Jeepify-Monitor240

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_BtnTxt[2] = {0xDBDBDB, 0x333333};
const ui_theme_variable_t _ui_theme_alpha_BtnTxt[2] = {255, 200};

const ui_theme_variable_t _ui_theme_color_BtnBg[2] = {0xAD0808, 0xAD0808};
const ui_theme_variable_t _ui_theme_alpha_BtnBg[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_BtnBorder[2] = {0xDBDBDB, 0xDBDBDB};
const ui_theme_variable_t _ui_theme_alpha_BtnBorder[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_BtnSelected[2] = {0x740303, 0x740303};
const ui_theme_variable_t _ui_theme_alpha_BtnSelected[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_BtnTxtInaktive[2] = {0x000000, 0x000000};
const ui_theme_variable_t _ui_theme_alpha_BtnTxtInaktive[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

