// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SQ-Jeepify-Monitor240

#ifndef UI_SCRPEERS_H
#define UI_SCRPEERS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScrPeers
extern void ui_ScrPeers_screen_init(void);
extern void ui_ScrPeers_screen_destroy(void);
extern void ui_event_ScrPeers(lv_event_t * e);
extern lv_obj_t * ui_ScrPeers;
extern lv_obj_t * ui_RollerPeers1;
extern lv_obj_t * ui_LabelPeersName;
extern void ui_event_BtnPeer9(lv_event_t * e);
extern lv_obj_t * ui_BtnPeer9;
extern lv_obj_t * ui_BtnPeer4Lbl4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

