// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SQ-Jeepify-Monitor240

#ifndef UI_SCRMULTI_H
#define UI_SCRMULTI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScrMulti
extern void ui_ScrMulti_screen_init(void);
extern void ui_ScrMulti_screen_destroy(void);
extern void ui_event_ScrMulti(lv_event_t * e);
extern lv_obj_t * ui_ScrMulti;
extern lv_obj_t * ui_LblMultiScreenName;
extern lv_obj_t * ui_Container2;
extern void ui_event_ButtonMulti1(lv_event_t * e);
extern lv_obj_t * ui_ButtonMulti1;
extern lv_obj_t * ui_Label6;
extern void ui_event_ButtonMulti2(lv_event_t * e);
extern lv_obj_t * ui_ButtonMulti2;
extern lv_obj_t * ui_Label2;
extern void ui_event_ButtonMulti3(lv_event_t * e);
extern lv_obj_t * ui_ButtonMulti3;
extern lv_obj_t * ui_Label3;
extern void ui_event_ButtonMulti4(lv_event_t * e);
extern lv_obj_t * ui_ButtonMulti4;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

