// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SQ-Jeepify-Monitor240

#include "../ui.h"

lv_obj_t * ui_ScrPeriph = NULL;
lv_obj_t * ui_ImgPeerChoice = NULL;
lv_obj_t * ui_LblPeriphChoicePeer = NULL;
lv_obj_t * ui_LblPeriphChoiceType = NULL;
lv_obj_t * ui_LblPeriphChoiceOnline = NULL;
lv_obj_t * ui_LblPeriphChoicePeriph = NULL;
// event funtions
void ui_event_ScrPeriph(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrMulti, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_ScrMulti_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        Ui_PeriphChoice_Next(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        Ui_PeriphChoice_Last(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        Ui_PeriphChoice_Click(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        Ui_Periph_Choice_Loaded(e);
    }
}

// build funtions

void ui_ScrPeriph_screen_init(void)
{
    ui_ScrPeriph = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrPeriph, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrPeriph, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrPeriph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ScrPeriph, &ui_img_jeepifybackground_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrPeriph, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgPeerChoice = lv_img_create(ui_ScrPeriph);
    lv_img_set_src(ui_ImgPeerChoice, &ui_img_menubtn2_png);
    lv_obj_set_width(ui_ImgPeerChoice, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_ImgPeerChoice, LV_SIZE_CONTENT);    /// 79
    lv_obj_set_x(ui_ImgPeerChoice, -2);
    lv_obj_set_y(ui_ImgPeerChoice, -65);
    lv_obj_set_align(ui_ImgPeerChoice, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgPeerChoice, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgPeerChoice, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblPeriphChoicePeer = lv_label_create(ui_ScrPeriph);
    lv_obj_set_width(ui_LblPeriphChoicePeer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblPeriphChoicePeer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblPeriphChoicePeer, 0);
    lv_obj_set_y(ui_LblPeriphChoicePeer, 85);
    lv_obj_set_align(ui_LblPeriphChoicePeer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblPeriphChoicePeer, "Peer");
    lv_obj_set_style_text_color(ui_LblPeriphChoicePeer, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblPeriphChoicePeer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblPeriphChoiceType = lv_label_create(ui_ScrPeriph);
    lv_obj_set_width(ui_LblPeriphChoiceType, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblPeriphChoiceType, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblPeriphChoiceType, 0);
    lv_obj_set_y(ui_LblPeriphChoiceType, 25);
    lv_obj_set_align(ui_LblPeriphChoiceType, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblPeriphChoiceType, "Type: ");
    lv_obj_set_style_text_color(ui_LblPeriphChoiceType, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblPeriphChoiceType, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblPeriphChoiceOnline = lv_label_create(ui_ScrPeriph);
    lv_obj_set_width(ui_LblPeriphChoiceOnline, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblPeriphChoiceOnline, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblPeriphChoiceOnline, -1);
    lv_obj_set_y(ui_LblPeriphChoiceOnline, 50);
    lv_obj_set_align(ui_LblPeriphChoiceOnline, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblPeriphChoiceOnline, "Online");
    lv_obj_set_style_text_color(ui_LblPeriphChoiceOnline, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblPeriphChoiceOnline, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblPeriphChoicePeriph = lv_label_create(ui_ScrPeriph);
    lv_obj_set_width(ui_LblPeriphChoicePeriph, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblPeriphChoicePeriph, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblPeriphChoicePeriph, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblPeriphChoicePeriph, "Name");
    lv_obj_set_style_text_color(ui_LblPeriphChoicePeriph, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblPeriphChoicePeriph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScrPeriph, ui_event_ScrPeriph, LV_EVENT_ALL, NULL);

}

void ui_ScrPeriph_screen_destroy(void)
{
    if(ui_ScrPeriph) lv_obj_del(ui_ScrPeriph);

    // NULL screen variables
    ui_ScrPeriph = NULL;
    ui_ImgPeerChoice = NULL;
    ui_LblPeriphChoicePeer = NULL;
    ui_LblPeriphChoiceType = NULL;
    ui_LblPeriphChoiceOnline = NULL;
    ui_LblPeriphChoicePeriph = NULL;

}
