// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SQ-Jeepify-Monitor240

#include "../ui.h"

lv_obj_t * ui_ScrPeers = NULL;
lv_obj_t * ui_RollerPeers1 = NULL;
lv_obj_t * ui_LabelPeersName = NULL;
lv_obj_t * ui_BtnPeer9 = NULL;
lv_obj_t * ui_BtnPeer4Lbl4 = NULL;
// event funtions
void ui_event_ScrPeers(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        Ui_Peers_Prepare(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrMenu, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_ScrMenu_screen_init);
    }
}

void ui_event_BtnPeer9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Ui_Peers_Selected(e);
    }
}

// build funtions

void ui_ScrPeers_screen_init(void)
{
    ui_ScrPeers = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrPeers, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrPeers, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrPeers, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ScrPeers, &ui_img_jeepifybackground_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerPeers1 = lv_roller_create(ui_ScrPeers);
    lv_roller_set_options(ui_RollerPeers1, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_RollerPeers1, lv_pct(70));
    lv_obj_set_height(ui_RollerPeers1, lv_pct(45));
    lv_obj_set_x(ui_RollerPeers1, 0);
    lv_obj_set_y(ui_RollerPeers1, -17);
    lv_obj_set_align(ui_RollerPeers1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_RollerPeers1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerPeers1, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerPeers1, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPeersName = lv_label_create(ui_ScrPeers);
    lv_obj_set_width(ui_LabelPeersName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPeersName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPeersName, 0);
    lv_obj_set_y(ui_LabelPeersName, 85);
    lv_obj_set_align(ui_LabelPeersName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPeersName, "Peers");
    lv_obj_set_style_text_color(ui_LabelPeersName, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPeersName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPeersName, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPeer9 = lv_btn_create(ui_ScrPeers);
    lv_obj_set_width(ui_BtnPeer9, lv_pct(30));
    lv_obj_set_height(ui_BtnPeer9, lv_pct(10));
    lv_obj_set_x(ui_BtnPeer9, lv_pct(20));
    lv_obj_set_y(ui_BtnPeer9, lv_pct(23));
    lv_obj_set_align(ui_BtnPeer9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnPeer9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPeer9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnPeer9, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnPeer9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnPeer9, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnPeer9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnPeer9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BtnPeer9, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPeer4Lbl4 = lv_label_create(ui_BtnPeer9);
    lv_obj_set_width(ui_BtnPeer4Lbl4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnPeer4Lbl4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnPeer4Lbl4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnPeer4Lbl4, "show");

    lv_obj_add_event_cb(ui_BtnPeer9, ui_event_BtnPeer9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrPeers, ui_event_ScrPeers, LV_EVENT_ALL, NULL);

}

void ui_ScrPeers_screen_destroy(void)
{
    if(ui_ScrPeers) lv_obj_del(ui_ScrPeers);

    // NULL screen variables
    ui_ScrPeers = NULL;
    ui_RollerPeers1 = NULL;
    ui_LabelPeersName = NULL;
    ui_BtnPeer9 = NULL;
    ui_BtnPeer4Lbl4 = NULL;

}
