// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SQ-Jeepify-Monitor-All

#include "../ui.h"

void ui_comp_ButtonSensorSmall_create_hook(lv_obj_t * comp)
{
}
