// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SQ-Jeepify-Monitor360

#ifndef UI_SCRPERIPH_H
#define UI_SCRPERIPH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScrPeriph
extern void ui_ScrPeriph_screen_init(void);
extern void ui_ScrPeriph_screen_destroy(void);
extern void ui_event_ScrPeriph(lv_event_t * e);
extern lv_obj_t * ui_ScrPeriph;
extern lv_obj_t * ui_ImgPeerChoice;
extern lv_obj_t * ui_LblPeriphChoicePeer;
extern lv_obj_t * ui_LblPeriphChoiceType;
extern lv_obj_t * ui_LblPeriphChoiceOnline;
extern lv_obj_t * ui_LblPeriphChoicePeriph;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

