// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SQ-Jeepify-Monitor360

#include "../ui.h"

lv_obj_t * ui_ScrSystem = NULL;
lv_obj_t * ui_LblSystemPeer = NULL;
lv_obj_t * ui_LblSystemLeft = NULL;
lv_obj_t * ui_LblSystemRight = NULL;
// event funtions
void ui_event_ScrSystem(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        Ui_JSON_Prepare(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrSettings, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_ScrSettings_screen_init);
    }
}

void ui_event_LblSystemRight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrPeer, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_ScrPeer_screen_init);
    }
}

// build funtions

void ui_ScrSystem_screen_init(void)
{
    ui_ScrSystem = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrSystem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrSystem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrSystem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ScrSystem, &ui_img_jeepifybackground_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrSystem, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblSystemPeer = lv_label_create(ui_ScrSystem);
    lv_obj_set_width(ui_LblSystemPeer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblSystemPeer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblSystemPeer, 5);
    lv_obj_set_y(ui_LblSystemPeer, 132);
    lv_obj_set_align(ui_LblSystemPeer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblSystemPeer, "Peer");
    lv_obj_set_style_text_color(ui_LblSystemPeer, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblSystemPeer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblSystemPeer, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblSystemLeft = lv_textarea_create(ui_ScrSystem);
    lv_obj_set_width(ui_LblSystemLeft, 90);
    lv_obj_set_height(ui_LblSystemLeft, 211);
    lv_obj_set_x(ui_LblSystemLeft, -90);
    lv_obj_set_y(ui_LblSystemLeft, -13);
    lv_obj_set_align(ui_LblSystemLeft, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_LblSystemLeft, "P1   -\nP2   -\nP3   -\nP4\nP5\nP6\nP7\nP8\nP9");
    lv_textarea_set_placeholder_text(ui_LblSystemLeft, "Placeholder...");
    lv_obj_clear_flag(ui_LblSystemLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_LblSystemLeft, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_BtnTxt);
    ui_object_set_themeable_style_property(ui_LblSystemLeft, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_BtnTxt);
    lv_obj_set_style_text_align(ui_LblSystemLeft, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LblSystemLeft, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LblSystemLeft, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblSystemRight = lv_textarea_create(ui_ScrSystem);
    lv_obj_set_width(ui_LblSystemRight, 170);
    lv_obj_set_height(ui_LblSystemRight, 211);
    lv_obj_set_x(ui_LblSystemRight, 49);
    lv_obj_set_y(ui_LblSystemRight, -12);
    lv_obj_set_align(ui_LblSystemRight, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_LblSystemRight, "P1   -\nP2   -\nP3   -\nP4\nP5\nP6\nP7\nP8\nP9");
    lv_textarea_set_placeholder_text(ui_LblSystemRight, "Placeholder...");
    lv_obj_add_flag(ui_LblSystemRight, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_LblSystemRight,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_LblSystemRight, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_BtnTxt);
    ui_object_set_themeable_style_property(ui_LblSystemRight, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_BtnTxt);
    lv_obj_set_style_text_align(ui_LblSystemRight, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LblSystemRight, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LblSystemRight, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_LblSystemRight, ui_event_LblSystemRight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrSystem, ui_event_ScrSystem, LV_EVENT_ALL, NULL);

}

void ui_ScrSystem_screen_destroy(void)
{
    if(ui_ScrSystem) lv_obj_del(ui_ScrSystem);

    // NULL screen variables
    ui_ScrSystem = NULL;
    ui_LblSystemPeer = NULL;
    ui_LblSystemLeft = NULL;
    ui_LblSystemRight = NULL;

}
