// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SQ-Jeepify-Monitor360

#ifndef UI_SCRPEER_H
#define UI_SCRPEER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScrPeer
extern void ui_ScrPeer_screen_init(void);
extern void ui_ScrPeer_screen_destroy(void);
extern void ui_event_ScrPeer(lv_event_t * e);
extern lv_obj_t * ui_ScrPeer;
extern lv_obj_t * ui_ImgPeerType;
extern lv_obj_t * ui_LblPeerName;
extern lv_obj_t * ui_LblPeerTypeLbl;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Container3;
extern void ui_event_BtnPeer1(lv_event_t * e);
extern lv_obj_t * ui_BtnPeer1;
extern void ui_event_BtnPeer1Lbl(lv_event_t * e);
extern lv_obj_t * ui_BtnPeer1Lbl;
extern void ui_event_BtnPeer2(lv_event_t * e);
extern lv_obj_t * ui_BtnPeer2;
extern lv_obj_t * ui_BtnPeer2Lbl1;
extern void ui_event_BtnPeer3(lv_event_t * e);
extern lv_obj_t * ui_BtnPeer3;
extern lv_obj_t * ui_BtnPeer3Lbl1;
extern void ui_event_BtnPeer5(lv_event_t * e);
extern lv_obj_t * ui_BtnPeer5;
extern lv_obj_t * ui_BtnPeer5Lbl1;
extern void ui_event_BtnPeer6(lv_event_t * e);
extern lv_obj_t * ui_BtnPeer6;
extern lv_obj_t * ui_BtnPeer6Lbl1;
extern void ui_event_BtnPeer4(lv_event_t * e);
extern lv_obj_t * ui_BtnPeer4;
extern lv_obj_t * ui_BtnPeer4Lbl1;
extern void ui_event_BtnPeer7(lv_event_t * e);
extern lv_obj_t * ui_BtnPeer7;
extern void ui_event_BtnPeer7Lbl1(lv_event_t * e);
extern lv_obj_t * ui_BtnPeer7Lbl1;
extern lv_obj_t * ui_BtnPeer10;
extern void ui_event_BtnPeer7Lbl3(lv_event_t * e);
extern lv_obj_t * ui_BtnPeer7Lbl3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

