// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SQ-Jeepify-Monitor360

#ifndef UI_SCRVOLT_H
#define UI_SCRVOLT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScrVolt
extern void ui_ScrVolt_screen_init(void);
extern void ui_ScrVolt_screen_destroy(void);
extern void ui_event_ScrVolt(lv_event_t * e);
extern lv_obj_t * ui_ScrVolt;
extern void ui_event_Keyboard(lv_event_t * e);
extern lv_obj_t * ui_Keyboard;
extern lv_obj_t * ui_TxtVolt;
extern void ui_event_LblVoltPeer(lv_event_t * e);
extern lv_obj_t * ui_LblVoltPeer;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

