// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SQ-Jeepify-Monitor480

#include "ui.h"

lv_obj_t * ui_ScrPeer = NULL;
lv_obj_t * ui_ImgPeerType = NULL;
lv_obj_t * ui_LblPeerName = NULL;
lv_obj_t * ui_LblPeerTypeLbl = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_BtnPeer1 = NULL;
lv_obj_t * ui_BtnPeer1Lbl = NULL;
lv_obj_t * ui_BtnPeer2 = NULL;
lv_obj_t * ui_BtnPeer2Lbl1 = NULL;
lv_obj_t * ui_BtnPeer3 = NULL;
lv_obj_t * ui_BtnPeer3Lbl1 = NULL;
lv_obj_t * ui_BtnPeer5 = NULL;
lv_obj_t * ui_BtnPeer5Lbl1 = NULL;
lv_obj_t * ui_BtnPeer6 = NULL;
lv_obj_t * ui_BtnPeer6Lbl1 = NULL;
lv_obj_t * ui_BtnPeer4 = NULL;
lv_obj_t * ui_BtnPeer4Lbl1 = NULL;
lv_obj_t * ui_BtnPeer7 = NULL;
lv_obj_t * ui_BtnPeer7Lbl1 = NULL;
lv_obj_t * ui_BtnPeer10 = NULL;
lv_obj_t * ui_BtnPeer7Lbl3 = NULL;
// event funtions
void ui_event_ScrPeer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        Ui_Peer_Loaded(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        Ui_Peer_Next(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        Ui_Peer_Last(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrMenu, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_ScrMenu_screen_init);
    }
}

void ui_event_BtnPeer1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Ui_Peer_Restart(e);
    }
}

void ui_event_BtnPeer1Lbl(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Ui_Peer_Restart(e);
    }
}

void ui_event_BtnPeer2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        Ui_Peer_Reset(e);
    }
}

void ui_event_BtnPeer3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Ui_Peer_ToggleSleep(e);
    }
}

void ui_event_BtnPeer5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScrVolt, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_ScrVolt_screen_init);
    }
}

void ui_event_BtnPeer6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Ui_Peer_ToggleDemo(e);
    }
}

void ui_event_BtnPeer4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScrEichen, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_ScrEichen_screen_init);
    }
}

void ui_event_BtnPeer7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        Ui_Peer_Delete(e);
    }
}

void ui_event_BtnPeer7Lbl1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Ui_Peer_Restart(e);
    }
}

void ui_event_BtnPeer7Lbl3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Ui_Peer_Restart(e);
    }
}

// build funtions

void ui_ScrPeer_screen_init(void)
{
    ui_ScrPeer = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrPeer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrPeer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrPeer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ScrPeer, &ui_img_jeepifybackground_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrPeer, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgPeerType = lv_img_create(ui_ScrPeer);
    lv_img_set_src(ui_ImgPeerType, &ui_img_ansgarmodule_4_png);
    lv_obj_set_width(ui_ImgPeerType, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgPeerType, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgPeerType, 28);
    lv_obj_set_y(ui_ImgPeerType, -75);
    lv_obj_set_align(ui_ImgPeerType, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgPeerType, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgPeerType, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblPeerName = lv_label_create(ui_ScrPeer);
    lv_obj_set_width(ui_LblPeerName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblPeerName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblPeerName, -3);
    lv_obj_set_y(ui_LblPeerName, 129);
    lv_obj_set_align(ui_LblPeerName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblPeerName, "Peer");
    lv_obj_set_style_text_color(ui_LblPeerName, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblPeerName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblPeerName, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblPeerTypeLbl = lv_label_create(ui_ScrPeer);
    lv_obj_set_width(ui_LblPeerTypeLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblPeerTypeLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblPeerTypeLbl, -7);
    lv_obj_set_y(ui_LblPeerTypeLbl, -145);
    lv_obj_set_align(ui_LblPeerTypeLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblPeerTypeLbl, "Type:");
    lv_obj_add_flag(ui_LblPeerTypeLbl, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LblPeerTypeLbl, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblPeerTypeLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblPeerTypeLbl, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_ScrPeer);
    lv_img_set_src(ui_Image2, &ui_img_friedermodule_disp_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, 93);
    lv_obj_set_y(ui_Image2, -73);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_ScrPeer);
    lv_img_set_src(ui_Image3, &ui_img_horstrelais2_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, -95);
    lv_obj_set_y(ui_Image3, -70);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_ScrPeer);
    lv_img_set_src(ui_Image4, &ui_img_1769637049);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, -83);
    lv_obj_set_y(ui_Image4, 110);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_ScrPeer);
    lv_img_set_src(ui_Image5, &ui_img_rolfmodule_round_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, 75);
    lv_obj_set_y(ui_Image5, 112);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container3 = lv_obj_create(ui_ScrPeer);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, lv_pct(90));
    lv_obj_set_height(ui_Container3, lv_pct(90));
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Container3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_BtnTxt);
    ui_object_set_themeable_style_property(ui_Container3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_BtnTxt);

    ui_BtnPeer1 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_BtnPeer1, lv_pct(40));
    lv_obj_set_height(ui_BtnPeer1, lv_pct(15));
    lv_obj_set_x(ui_BtnPeer1, lv_pct(-20));
    lv_obj_set_y(ui_BtnPeer1, lv_pct(-10));
    lv_obj_set_align(ui_BtnPeer1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnPeer1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPeer1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnPeer1, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnPeer1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnPeer1, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnPeer1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnPeer1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPeer1Lbl = lv_label_create(ui_BtnPeer1);
    lv_obj_set_width(ui_BtnPeer1Lbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnPeer1Lbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnPeer1Lbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnPeer1Lbl, "Restart");

    ui_BtnPeer2 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_BtnPeer2, lv_pct(40));
    lv_obj_set_height(ui_BtnPeer2, lv_pct(15));
    lv_obj_set_x(ui_BtnPeer2, lv_pct(20));
    lv_obj_set_y(ui_BtnPeer2, lv_pct(-10));
    lv_obj_set_align(ui_BtnPeer2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnPeer2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPeer2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnPeer2, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnPeer2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnPeer2, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnPeer2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnPeer2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPeer2Lbl1 = lv_label_create(ui_BtnPeer2);
    lv_obj_set_width(ui_BtnPeer2Lbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnPeer2Lbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnPeer2Lbl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnPeer2Lbl1, "Reset");

    ui_BtnPeer3 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_BtnPeer3, lv_pct(40));
    lv_obj_set_height(ui_BtnPeer3, lv_pct(15));
    lv_obj_set_x(ui_BtnPeer3, lv_pct(-20));
    lv_obj_set_y(ui_BtnPeer3, lv_pct(5));
    lv_obj_set_align(ui_BtnPeer3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnPeer3, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPeer3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnPeer3, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnPeer3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnPeer3, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnPeer3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnPeer3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPeer3Lbl1 = lv_label_create(ui_BtnPeer3);
    lv_obj_set_width(ui_BtnPeer3Lbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnPeer3Lbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnPeer3Lbl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnPeer3Lbl1, "Sleep");

    ui_BtnPeer5 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_BtnPeer5, lv_pct(40));
    lv_obj_set_height(ui_BtnPeer5, lv_pct(15));
    lv_obj_set_x(ui_BtnPeer5, lv_pct(-20));
    lv_obj_set_y(ui_BtnPeer5, lv_pct(20));
    lv_obj_set_align(ui_BtnPeer5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnPeer5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPeer5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnPeer5, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnPeer5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnPeer5, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnPeer5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnPeer5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPeer5Lbl1 = lv_label_create(ui_BtnPeer5);
    lv_obj_set_width(ui_BtnPeer5Lbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnPeer5Lbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnPeer5Lbl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnPeer5Lbl1, "Volt");

    ui_BtnPeer6 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_BtnPeer6, lv_pct(40));
    lv_obj_set_height(ui_BtnPeer6, lv_pct(15));
    lv_obj_set_x(ui_BtnPeer6, lv_pct(20));
    lv_obj_set_y(ui_BtnPeer6, lv_pct(20));
    lv_obj_set_align(ui_BtnPeer6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnPeer6, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPeer6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnPeer6, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnPeer6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnPeer6, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnPeer6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnPeer6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPeer6Lbl1 = lv_label_create(ui_BtnPeer6);
    lv_obj_set_width(ui_BtnPeer6Lbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnPeer6Lbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnPeer6Lbl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnPeer6Lbl1, "Demo");
    lv_obj_add_flag(ui_BtnPeer6Lbl1, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    ui_BtnPeer4 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_BtnPeer4, lv_pct(40));
    lv_obj_set_height(ui_BtnPeer4, lv_pct(15));
    lv_obj_set_x(ui_BtnPeer4, lv_pct(20));
    lv_obj_set_y(ui_BtnPeer4, lv_pct(5));
    lv_obj_set_align(ui_BtnPeer4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnPeer4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPeer4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnPeer4, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnPeer4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnPeer4, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnPeer4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnPeer4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPeer4Lbl1 = lv_label_create(ui_BtnPeer4);
    lv_obj_set_width(ui_BtnPeer4Lbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnPeer4Lbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnPeer4Lbl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnPeer4Lbl1, "Eichen");

    ui_BtnPeer7 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_BtnPeer7, lv_pct(40));
    lv_obj_set_height(ui_BtnPeer7, lv_pct(15));
    lv_obj_set_x(ui_BtnPeer7, lv_pct(-63));
    lv_obj_set_y(ui_BtnPeer7, lv_pct(-21));
    lv_obj_set_align(ui_BtnPeer7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnPeer7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPeer7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnPeer7, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnPeer7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnPeer7, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnPeer7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnPeer7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPeer7Lbl1 = lv_label_create(ui_BtnPeer7);
    lv_obj_set_width(ui_BtnPeer7Lbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnPeer7Lbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnPeer7Lbl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnPeer7Lbl1, "Delete");

    ui_BtnPeer10 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_BtnPeer10, lv_pct(40));
    lv_obj_set_height(ui_BtnPeer10, lv_pct(15));
    lv_obj_set_x(ui_BtnPeer10, lv_pct(-63));
    lv_obj_set_y(ui_BtnPeer10, lv_pct(-21));
    lv_obj_set_align(ui_BtnPeer10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnPeer10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPeer10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnPeer10, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnPeer10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnPeer10, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnPeer10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnPeer10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPeer7Lbl3 = lv_label_create(ui_BtnPeer10);
    lv_obj_set_width(ui_BtnPeer7Lbl3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnPeer7Lbl3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnPeer7Lbl3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnPeer7Lbl3, "System");

    lv_obj_add_event_cb(ui_BtnPeer1Lbl, ui_event_BtnPeer1Lbl, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnPeer1, ui_event_BtnPeer1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnPeer2, ui_event_BtnPeer2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnPeer3, ui_event_BtnPeer3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnPeer5, ui_event_BtnPeer5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnPeer6, ui_event_BtnPeer6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnPeer4, ui_event_BtnPeer4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnPeer7Lbl1, ui_event_BtnPeer7Lbl1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnPeer7, ui_event_BtnPeer7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnPeer7Lbl3, ui_event_BtnPeer7Lbl3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrPeer, ui_event_ScrPeer, LV_EVENT_ALL, NULL);

}

void ui_ScrPeer_screen_destroy(void)
{
    if(ui_ScrPeer) lv_obj_del(ui_ScrPeer);

    // NULL screen variables
    ui_ScrPeer = NULL;
    ui_ImgPeerType = NULL;
    ui_LblPeerName = NULL;
    ui_LblPeerTypeLbl = NULL;
    ui_Image2 = NULL;
    ui_Image3 = NULL;
    ui_Image4 = NULL;
    ui_Image5 = NULL;
    ui_Container3 = NULL;
    ui_BtnPeer1 = NULL;
    ui_BtnPeer1Lbl = NULL;
    ui_BtnPeer2 = NULL;
    ui_BtnPeer2Lbl1 = NULL;
    ui_BtnPeer3 = NULL;
    ui_BtnPeer3Lbl1 = NULL;
    ui_BtnPeer5 = NULL;
    ui_BtnPeer5Lbl1 = NULL;
    ui_BtnPeer6 = NULL;
    ui_BtnPeer6Lbl1 = NULL;
    ui_BtnPeer4 = NULL;
    ui_BtnPeer4Lbl1 = NULL;
    ui_BtnPeer7 = NULL;
    ui_BtnPeer7Lbl1 = NULL;
    ui_BtnPeer10 = NULL;
    ui_BtnPeer7Lbl3 = NULL;

}
