// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SQ-Jeepify-Monitor480

#include "ui.h"

lv_obj_t * ui_ScrMulti = NULL;
lv_obj_t * ui_LblMultiScreenName = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_ButtonMulti1 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_ButtonMulti2 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_ButtonMulti3 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_ButtonMulti4 = NULL;
lv_obj_t * ui_Label4 = NULL;
// event funtions
void ui_event_ScrMulti(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrMenu, LV_SCR_LOAD_ANIM_MOVE_TOP, 50, 0, &ui_ScrMenu_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        Ui_Multi_Loaded(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        Ui_Multi_Unload(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        Ui_Multi_Next(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        Ui_Multi_Prev(e);
    }
}

void ui_event_ButtonMulti1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Ui_Multi_Set_Panel1(e);
    }
}

void ui_event_ButtonMulti2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Ui_Multi_Set_Panel2(e);
    }
}

void ui_event_ButtonMulti3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Ui_Multi_Set_Panel3(e);
    }
}

void ui_event_ButtonMulti4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Ui_Multi_Set_Panel4(e);
    }
}

// build funtions

void ui_ScrMulti_screen_init(void)
{
    ui_ScrMulti = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrMulti, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrMulti, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrMulti, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ScrMulti, &ui_img_jeepifybackground_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrMulti, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblMultiScreenName = lv_label_create(ui_ScrMulti);
    lv_obj_set_width(ui_LblMultiScreenName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblMultiScreenName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblMultiScreenName, 0);
    lv_obj_set_y(ui_LblMultiScreenName, -148);
    lv_obj_set_align(ui_LblMultiScreenName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblMultiScreenName, "Screen");
    lv_obj_set_style_text_color(ui_LblMultiScreenName, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblMultiScreenName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_ScrMulti);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, lv_pct(76));
    lv_obj_set_height(ui_Container2, lv_pct(72));
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonMulti1 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_ButtonMulti1, lv_pct(40));
    lv_obj_set_height(ui_ButtonMulti1, lv_pct(40));
    lv_obj_set_x(ui_ButtonMulti1, lv_pct(-25));
    lv_obj_set_y(ui_ButtonMulti1, lv_pct(-25));
    lv_obj_set_align(ui_ButtonMulti1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonMulti1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonMulti1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonMulti1, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonMulti1, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMulti1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonMulti1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonMulti1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_ButtonMulti1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "+");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonMulti2 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_ButtonMulti2, lv_pct(40));
    lv_obj_set_height(ui_ButtonMulti2, lv_pct(40));
    lv_obj_set_x(ui_ButtonMulti2, lv_pct(25));
    lv_obj_set_y(ui_ButtonMulti2, lv_pct(-25));
    lv_obj_set_align(ui_ButtonMulti2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonMulti2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonMulti2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonMulti2, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonMulti2, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMulti2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonMulti2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonMulti2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_ButtonMulti2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "+");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonMulti3 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_ButtonMulti3, lv_pct(40));
    lv_obj_set_height(ui_ButtonMulti3, lv_pct(40));
    lv_obj_set_x(ui_ButtonMulti3, lv_pct(-25));
    lv_obj_set_y(ui_ButtonMulti3, lv_pct(25));
    lv_obj_set_align(ui_ButtonMulti3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonMulti3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonMulti3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonMulti3, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonMulti3, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMulti3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonMulti3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonMulti3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_ButtonMulti3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "+");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonMulti4 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_ButtonMulti4, lv_pct(40));
    lv_obj_set_height(ui_ButtonMulti4, lv_pct(40));
    lv_obj_set_x(ui_ButtonMulti4, lv_pct(25));
    lv_obj_set_y(ui_ButtonMulti4, lv_pct(25));
    lv_obj_set_align(ui_ButtonMulti4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonMulti4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonMulti4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonMulti4, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonMulti4, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMulti4, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonMulti4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonMulti4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_ButtonMulti4);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "+");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonMulti1, ui_event_ButtonMulti1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonMulti2, ui_event_ButtonMulti2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonMulti3, ui_event_ButtonMulti3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonMulti4, ui_event_ButtonMulti4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrMulti, ui_event_ScrMulti, LV_EVENT_ALL, NULL);

}

void ui_ScrMulti_screen_destroy(void)
{
    if(ui_ScrMulti) lv_obj_del(ui_ScrMulti);

    // NULL screen variables
    ui_ScrMulti = NULL;
    ui_LblMultiScreenName = NULL;
    ui_Container2 = NULL;
    ui_ButtonMulti1 = NULL;
    ui_Label6 = NULL;
    ui_ButtonMulti2 = NULL;
    ui_Label2 = NULL;
    ui_ButtonMulti3 = NULL;
    ui_Label3 = NULL;
    ui_ButtonMulti4 = NULL;
    ui_Label4 = NULL;

}
