// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SQ-Jeepify-Monitor480

#ifndef UI_SCRMENU_H
#define UI_SCRMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScrMenu
extern void ui_ScrMenu_screen_init(void);
extern void ui_ScrMenu_screen_destroy(void);
extern lv_obj_t * ui_ScrMenu;
extern lv_obj_t * ui_ImgRubicon;
extern lv_obj_t * ui_LblMenuVersion;
extern lv_obj_t * ui_Container4;
extern void ui_event_BtnMenu1(lv_event_t * e);
extern lv_obj_t * ui_BtnMenu1;
extern void ui_event_BtnMenu2(lv_event_t * e);
extern lv_obj_t * ui_BtnMenu2;
extern void ui_event_BtnMenu3(lv_event_t * e);
extern lv_obj_t * ui_BtnMenu3;
extern void ui_event_BtnMenu4(lv_event_t * e);
extern lv_obj_t * ui_BtnMenu4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

