// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SQ-Jeepify-Monitor480

#ifndef UI_SCRJSON_H
#define UI_SCRJSON_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScrJSON
extern void ui_ScrJSON_screen_init(void);
extern void ui_ScrJSON_screen_destroy(void);
extern void ui_event_ScrJSON(lv_event_t * e);
extern lv_obj_t * ui_ScrJSON;
extern lv_obj_t * ui_TxtJSON1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

