// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SQ-Jeepify-Monitor480

#ifndef UI_SCRSYSTEM_H
#define UI_SCRSYSTEM_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScrSystem
extern void ui_ScrSystem_screen_init(void);
extern void ui_ScrSystem_screen_destroy(void);
extern void ui_event_ScrSystem(lv_event_t * e);
extern lv_obj_t * ui_ScrSystem;
extern lv_obj_t * ui_LblSystemPeer;
extern lv_obj_t * ui_LblSystemLeft;
extern void ui_event_LblSystemRight(lv_event_t * e);
extern lv_obj_t * ui_LblSystemRight;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

