// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SQ-Jeepify-Monitor480

#include "ui.h"

lv_obj_t * ui_ScrSettings = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_BtnSet1 = NULL;
lv_obj_t * ui_BtnSet1Lbl1 = NULL;
lv_obj_t * ui_BtnSet2 = NULL;
lv_obj_t * ui_BtnSet2Lbl = NULL;
lv_obj_t * ui_BtnSet3 = NULL;
lv_obj_t * ui_BtnSet3Lbl3 = NULL;
lv_obj_t * ui_BtnSet4 = NULL;
lv_obj_t * ui_BtnSet3Lbl1 = NULL;
lv_obj_t * ui_BtnSet5 = NULL;
lv_obj_t * ui_BtnSet5Lbl = NULL;
lv_obj_t * ui_BtnSet6 = NULL;
lv_obj_t * ui_BtnSet3Lbl2 = NULL;
lv_obj_t * ui_BtnSet7 = NULL;
lv_obj_t * ui_BtnSet7Lbl = NULL;
lv_obj_t * ui_BtnSet8 = NULL;
lv_obj_t * ui_BtnSet7Lbl1 = NULL;
// event funtions
void ui_event_ScrSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrMenu, LV_SCR_LOAD_ANIM_NONE, 50, 0, &ui_ScrMenu_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        Ui_Set_Prepare(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        Ui_Set_Leave(e);
    }
}

void ui_event_BtnSet1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Ui_Set_WebSvr(e);
    }
}

void ui_event_BtnSet2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Ui_Set_TogglePair(e);
    }
}

void ui_event_BtnSet3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Ui_Set_Restart(e);
    }
}

void ui_event_BtnSet4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        Ui_Set_Reset(e);
    }
}

void ui_event_BtnSet5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScrPeers, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_ScrPeers_screen_init);
    }
}

void ui_event_BtnSet6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScrJSON, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_ScrJSON_screen_init);
    }
}

void ui_event_BtnSet7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Ui_Set_ToggleDebug(e);
    }
}

void ui_event_BtnSet8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Ui_Set_SavePeers(e);
    }
}

// build funtions

void ui_ScrSettings_screen_init(void)
{
    ui_ScrSettings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrSettings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ScrSettings, &ui_img_jeepifybackground_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_ScrSettings);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, lv_pct(90));
    lv_obj_set_height(ui_Container1, lv_pct(90));
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Container1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSet1 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_BtnSet1, lv_pct(40));
    lv_obj_set_height(ui_BtnSet1, lv_pct(15));
    lv_obj_set_x(ui_BtnSet1, -40);
    lv_obj_set_y(ui_BtnSet1, 60);
    lv_obj_set_align(ui_BtnSet1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSet1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSet1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnSet1, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSet1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnSet1, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnSet1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnSet1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSet1Lbl1 = lv_label_create(ui_BtnSet1);
    lv_obj_set_width(ui_BtnSet1Lbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnSet1Lbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnSet1Lbl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnSet1Lbl1, "WebSvr");
    ui_object_set_themeable_style_property(ui_BtnSet1Lbl1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_BtnTxt);
    ui_object_set_themeable_style_property(ui_BtnSet1Lbl1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_BtnTxt);

    ui_BtnSet2 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_BtnSet2, lv_pct(40));
    lv_obj_set_height(ui_BtnSet2, lv_pct(15));
    lv_obj_set_x(ui_BtnSet2, 40);
    lv_obj_set_y(ui_BtnSet2, -60);
    lv_obj_set_align(ui_BtnSet2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSet2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSet2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnSet2, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSet2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnSet2, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnSet2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnSet2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnSet2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BtnSet2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_BtnSet2, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BtnSet2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_BtnSet2, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_BtnSet2, 50, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_BtnSet2Lbl = lv_label_create(ui_BtnSet2);
    lv_obj_set_width(ui_BtnSet2Lbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnSet2Lbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BtnSet2Lbl, 0);
    lv_obj_set_y(ui_BtnSet2Lbl, 1);
    lv_obj_set_align(ui_BtnSet2Lbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnSet2Lbl, "Pair");
    lv_obj_set_style_text_color(ui_BtnSet2Lbl, lv_color_hex(0xDDDDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnSet2Lbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSet3 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_BtnSet3, lv_pct(40));
    lv_obj_set_height(ui_BtnSet3, lv_pct(15));
    lv_obj_set_x(ui_BtnSet3, -40);
    lv_obj_set_y(ui_BtnSet3, -20);
    lv_obj_set_align(ui_BtnSet3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSet3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSet3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnSet3, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSet3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnSet3, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnSet3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnSet3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSet3Lbl3 = lv_label_create(ui_BtnSet3);
    lv_obj_set_width(ui_BtnSet3Lbl3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnSet3Lbl3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnSet3Lbl3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnSet3Lbl3, "Restart");
    lv_obj_set_style_text_color(ui_BtnSet3Lbl3, lv_color_hex(0xDDDDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnSet3Lbl3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSet4 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_BtnSet4, lv_pct(40));
    lv_obj_set_height(ui_BtnSet4, lv_pct(15));
    lv_obj_set_x(ui_BtnSet4, 40);
    lv_obj_set_y(ui_BtnSet4, -20);
    lv_obj_set_align(ui_BtnSet4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSet4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSet4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnSet4, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSet4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnSet4, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnSet4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnSet4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSet3Lbl1 = lv_label_create(ui_BtnSet4);
    lv_obj_set_width(ui_BtnSet3Lbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnSet3Lbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnSet3Lbl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnSet3Lbl1, "Reset");
    lv_obj_set_style_text_color(ui_BtnSet3Lbl1, lv_color_hex(0xDDDDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnSet3Lbl1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSet5 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_BtnSet5, lv_pct(40));
    lv_obj_set_height(ui_BtnSet5, lv_pct(15));
    lv_obj_set_x(ui_BtnSet5, -40);
    lv_obj_set_y(ui_BtnSet5, 20);
    lv_obj_set_align(ui_BtnSet5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSet5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSet5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnSet5, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSet5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnSet5, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnSet5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnSet5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSet5Lbl = lv_label_create(ui_BtnSet5);
    lv_obj_set_width(ui_BtnSet5Lbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnSet5Lbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnSet5Lbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnSet5Lbl, "Peers");
    lv_obj_set_style_text_color(ui_BtnSet5Lbl, lv_color_hex(0xDDDDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnSet5Lbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSet6 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_BtnSet6, lv_pct(40));
    lv_obj_set_height(ui_BtnSet6, lv_pct(15));
    lv_obj_set_x(ui_BtnSet6, 40);
    lv_obj_set_y(ui_BtnSet6, 20);
    lv_obj_set_align(ui_BtnSet6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSet6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSet6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnSet6, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSet6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnSet6, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnSet6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnSet6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSet3Lbl2 = lv_label_create(ui_BtnSet6);
    lv_obj_set_width(ui_BtnSet3Lbl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnSet3Lbl2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnSet3Lbl2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnSet3Lbl2, "JSON");
    lv_obj_set_style_text_color(ui_BtnSet3Lbl2, lv_color_hex(0xDDDDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnSet3Lbl2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSet7 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_BtnSet7, lv_pct(40));
    lv_obj_set_height(ui_BtnSet7, lv_pct(15));
    lv_obj_set_x(ui_BtnSet7, -40);
    lv_obj_set_y(ui_BtnSet7, -60);
    lv_obj_set_align(ui_BtnSet7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSet7, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSet7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnSet7, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSet7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnSet7, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnSet7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnSet7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnSet7, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BtnSet7, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_BtnSet7Lbl = lv_label_create(ui_BtnSet7);
    lv_obj_set_width(ui_BtnSet7Lbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnSet7Lbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnSet7Lbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnSet7Lbl, "Debug");
    lv_obj_set_style_text_color(ui_BtnSet7Lbl, lv_color_hex(0xDDDDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnSet7Lbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSet8 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_BtnSet8, lv_pct(40));
    lv_obj_set_height(ui_BtnSet8, lv_pct(15));
    lv_obj_set_x(ui_BtnSet8, 40);
    lv_obj_set_y(ui_BtnSet8, 60);
    lv_obj_set_align(ui_BtnSet8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSet8, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSet8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnSet8, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSet8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnSet8, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnSet8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnSet8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSet7Lbl1 = lv_label_create(ui_BtnSet8);
    lv_obj_set_width(ui_BtnSet7Lbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnSet7Lbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnSet7Lbl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnSet7Lbl1, "Save");
    lv_obj_set_style_text_color(ui_BtnSet7Lbl1, lv_color_hex(0xDDDDDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BtnSet7Lbl1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnSet1, ui_event_BtnSet1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSet2, ui_event_BtnSet2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSet3, ui_event_BtnSet3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSet4, ui_event_BtnSet4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSet5, ui_event_BtnSet5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSet6, ui_event_BtnSet6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSet7, ui_event_BtnSet7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSet8, ui_event_BtnSet8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrSettings, ui_event_ScrSettings, LV_EVENT_ALL, NULL);

}

void ui_ScrSettings_screen_destroy(void)
{
    if(ui_ScrSettings) lv_obj_del(ui_ScrSettings);

    // NULL screen variables
    ui_ScrSettings = NULL;
    ui_Container1 = NULL;
    ui_BtnSet1 = NULL;
    ui_BtnSet1Lbl1 = NULL;
    ui_BtnSet2 = NULL;
    ui_BtnSet2Lbl = NULL;
    ui_BtnSet3 = NULL;
    ui_BtnSet3Lbl3 = NULL;
    ui_BtnSet4 = NULL;
    ui_BtnSet3Lbl1 = NULL;
    ui_BtnSet5 = NULL;
    ui_BtnSet5Lbl = NULL;
    ui_BtnSet6 = NULL;
    ui_BtnSet3Lbl2 = NULL;
    ui_BtnSet7 = NULL;
    ui_BtnSet7Lbl = NULL;
    ui_BtnSet8 = NULL;
    ui_BtnSet7Lbl1 = NULL;

}
