// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SQ-Jeepify-Monitor360

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_BTNTXT 0
#define UI_THEME_COLOR_BTNBG 1
#define UI_THEME_COLOR_BTNBORDER 2
#define UI_THEME_COLOR_BTNSELECTED 3
#define UI_THEME_COLOR_BTNTXTINAKTIVE 4

#define UI_THEME_DEFAULT 0

#define UI_THEME_THEMEGREY2 1

extern const ui_theme_variable_t _ui_theme_color_BtnTxt[2];
extern const ui_theme_variable_t _ui_theme_alpha_BtnTxt[2];

extern const ui_theme_variable_t _ui_theme_color_BtnBg[2];
extern const ui_theme_variable_t _ui_theme_alpha_BtnBg[2];

extern const ui_theme_variable_t _ui_theme_color_BtnBorder[2];
extern const ui_theme_variable_t _ui_theme_alpha_BtnBorder[2];

extern const ui_theme_variable_t _ui_theme_color_BtnSelected[2];
extern const ui_theme_variable_t _ui_theme_alpha_BtnSelected[2];

extern const ui_theme_variable_t _ui_theme_color_BtnTxtInaktive[2];
extern const ui_theme_variable_t _ui_theme_alpha_BtnTxtInaktive[2];

extern const uint32_t * ui_theme_colors[2];
extern const uint8_t * ui_theme_alphas[2];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
