// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SQ-Jeepify-Monitor-All

#include "../ui.h"

lv_obj_t * ui_ScrJSON = NULL;
lv_obj_t * ui_ImgBGJSON = NULL;
lv_obj_t * ui_TxtJSON1 = NULL;
// event funtions
void ui_event_ScrJSON(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        Ui_JSON_Prepare(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrSettings, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_ScrSettings_screen_init);
    }
}

// build funtions

void ui_ScrJSON_screen_init(void)
{
    ui_ScrJSON = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrJSON, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrJSON, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrJSON, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrJSON, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgBGJSON = lv_img_create(ui_ScrJSON);
    lv_img_set_src(ui_ImgBGJSON, &ui_img_jeepifybackground_png);
    lv_obj_set_width(ui_ImgBGJSON, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgBGJSON, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgBGJSON, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgBGJSON, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgBGJSON, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_opa(ui_ImgBGJSON, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TxtJSON1 = lv_textarea_create(ui_ScrJSON);
    lv_obj_set_width(ui_TxtJSON1, lv_pct(74));
    lv_obj_set_height(ui_TxtJSON1, lv_pct(59));
    lv_obj_set_align(ui_TxtJSON1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TxtJSON1, "JSON-Message");
    lv_obj_set_style_text_color(ui_TxtJSON1, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TxtJSON1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TxtJSON1, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TxtJSON1, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScrJSON, ui_event_ScrJSON, LV_EVENT_ALL, NULL);

}

void ui_ScrJSON_screen_destroy(void)
{
    if(ui_ScrJSON) lv_obj_del(ui_ScrJSON);

    // NULL screen variables
    ui_ScrJSON = NULL;
    ui_ImgBGJSON = NULL;
    ui_TxtJSON1 = NULL;

}
