// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SQ-Jeepify-Monitor-All

#include "../ui.h"
#include <Arduino.h>

lv_obj_t * ui_ScrEichen = NULL;
lv_obj_t * ui_ImgBGEichen = NULL;
lv_obj_t * ui_LblEichenText = NULL;
lv_obj_t * ui_BtnEichenStart = NULL;
lv_obj_t * ui_LblBtnEichen = NULL;
lv_obj_t * ui_LblEichenPeer = NULL;
// event funtions
void ui_event_ScrEichen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrMenu, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_ScrMenu_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        Ui_Eichen_Prepare(e);
    }
}

void ui_event_BtnEichenStart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Ui_Eichen_Start(e);
    }
}

void ui_event_LblBtnEichen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        Ui_Eichen_Prepare(e);
    }
}

// build funtions

void ui_ScrEichen_screen_init(void)
{
    ui_ScrEichen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrEichen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrEichen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrEichen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScrEichen, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgBGEichen = lv_img_create(ui_ScrEichen);
    lv_img_set_src(ui_ImgBGEichen, &ui_img_jeepifybackground_png);
    lv_obj_set_width(ui_ImgBGEichen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgBGEichen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgBGEichen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgBGEichen, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgBGEichen, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_opa(ui_ImgBGEichen, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblEichenText = lv_label_create(ui_ScrEichen);
    lv_obj_set_width(ui_LblEichenText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblEichenText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblEichenText, 0);
    lv_obj_set_y(ui_LblEichenText, lv_pct(-20));
    lv_obj_set_align(ui_LblEichenText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblEichenText,
                      "Make sure, no devices \nare on the PDC's inputs\nStart, to calibrate input\ncurrent to 0 amps!");
    lv_obj_set_style_text_color(ui_LblEichenText, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblEichenText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnEichenStart = lv_btn_create(ui_ScrEichen);
    lv_obj_set_width(ui_BtnEichenStart, lv_pct(25));
    lv_obj_set_height(ui_BtnEichenStart, lv_pct(10));
    lv_obj_set_x(ui_BtnEichenStart, 0);
    lv_obj_set_y(ui_BtnEichenStart, lv_pct(12));
    lv_obj_set_align(ui_BtnEichenStart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnEichenStart, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnEichenStart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnEichenStart, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnEichenStart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnEichenStart, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnEichenStart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnEichenStart, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblBtnEichen = lv_label_create(ui_BtnEichenStart);
    lv_obj_set_width(ui_LblBtnEichen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblBtnEichen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblBtnEichen, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblBtnEichen, "Eichen");
    lv_obj_set_style_text_color(ui_LblBtnEichen, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblBtnEichen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblEichenPeer = lv_label_create(ui_ScrEichen);
    lv_obj_set_width(ui_LblEichenPeer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblEichenPeer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblEichenPeer, lv_pct(0));
    lv_obj_set_y(ui_LblEichenPeer, lv_pct(30));
    lv_obj_set_align(ui_LblEichenPeer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblEichenPeer, "Peer");
    lv_obj_set_style_text_color(ui_LblEichenPeer, lv_color_hex(0xAD0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblEichenPeer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_LblBtnEichen, ui_event_LblBtnEichen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnEichenStart, ui_event_BtnEichenStart, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScrEichen, ui_event_ScrEichen, LV_EVENT_ALL, NULL);

}

void ui_ScrEichen_screen_destroy(void)
{
    if(ui_ScrEichen) lv_obj_del(ui_ScrEichen);

    // NULL screen variables
    ui_ScrEichen = NULL;
    ui_ImgBGEichen = NULL;
    ui_LblEichenText = NULL;
    ui_BtnEichenStart = NULL;
    ui_LblBtnEichen = NULL;
    ui_LblEichenPeer = NULL;

}
