// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SQ-Jeepify-Monitor-All

#ifndef UI_SCRMULTIGAUGE_H
#define UI_SCRMULTIGAUGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScrMultiGauge
extern void ui_ScrMultiGauge_screen_init(void);
extern void ui_ScrMultiGauge_screen_destroy(void);
extern void ui_event_ScrMultiGauge(lv_event_t * e);
extern lv_obj_t * ui_ScrMultiGauge;
extern lv_obj_t * ui_ConMutiGauge;
extern lv_obj_t * ui_ArcAlternator;
extern lv_obj_t * ui_ArcSolar;
extern lv_obj_t * ui_ArcVerbrauch;
extern lv_obj_t * ui_KreisMG;
extern lv_obj_t * ui_LblMGVolt;
extern lv_obj_t * ui_LblMGAmp;
extern lv_obj_t * ui_LblMGArcLoad;
extern lv_obj_t * ui_LbLMGArcSolar;
extern lv_obj_t * ui_LblMGArcVerbrauch;
extern lv_obj_t * ui_ImgVerbrauch;
extern lv_obj_t * ui_ImgSolar;
extern lv_obj_t * ui_ImgLoad;
extern lv_obj_t * ui_LblName;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

