// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SQ-Jeepify-Monitor-All

#ifndef UI_SCREICHEN_H
#define UI_SCREICHEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScrEichen
extern void ui_ScrEichen_screen_init(void);
extern void ui_ScrEichen_screen_destroy(void);
extern void ui_event_ScrEichen(lv_event_t * e);
extern lv_obj_t * ui_ScrEichen;
extern lv_obj_t * ui_ImgBGEichen;
extern lv_obj_t * ui_LblEichenText;
extern void ui_event_BtnEichenStart(lv_event_t * e);
extern lv_obj_t * ui_BtnEichenStart;
extern void ui_event_LblBtnEichen(lv_event_t * e);
extern lv_obj_t * ui_LblBtnEichen;
extern lv_obj_t * ui_LblEichenPeer;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

