// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SQ-Jeepify-Monitor-All

#include "../ui.h"
#include "Jeepify.h"

lv_obj_t * ui_ScrMultiGauge = NULL;
lv_obj_t * ui_ConMutiGauge = NULL;
lv_obj_t * ui_ArcAlternator = NULL;
lv_obj_t * ui_ArcSolar = NULL;
lv_obj_t * ui_ArcVerbrauch = NULL;
lv_obj_t * ui_KreisMG = NULL;
lv_obj_t * ui_LblMGVolt = NULL;
lv_obj_t * ui_LblMGAmp = NULL;
lv_obj_t * ui_LblMGArcLoad = NULL;
lv_obj_t * ui_LbLMGArcSolar = NULL;
lv_obj_t * ui_LblMGArcVerbrauch = NULL;
lv_obj_t * ui_ImgVerbrauch = NULL;
lv_obj_t * ui_ImgSolar = NULL;
lv_obj_t * ui_ImgLoad = NULL;
lv_obj_t * ui_LblName = NULL;
// event funtions
void ui_event_ScrMultiGauge(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrMenu, MY_ANIM, 500, 0, &ui_ScrMenu_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        Ui_MultiGauge_Prepare(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        Ui_MultiGauge_Unload(e);
    }
}

// build funtions

void ui_ScrMultiGauge_screen_init(void)
{
    ui_ScrMultiGauge = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrMultiGauge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScrMultiGauge, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScrMultiGauge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConMutiGauge = lv_obj_create(ui_ScrMultiGauge);
    lv_obj_remove_style_all(ui_ConMutiGauge);
    lv_obj_set_width(ui_ConMutiGauge, 381);
    lv_obj_set_height(ui_ConMutiGauge, 364);
    lv_obj_set_align(ui_ConMutiGauge, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ConMutiGauge, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ArcAlternator = lv_arc_create(ui_ScrMultiGauge);
    lv_obj_set_width(ui_ArcAlternator, lv_pct(90));
    lv_obj_set_height(ui_ArcAlternator, lv_pct(90));
    lv_obj_set_align(ui_ArcAlternator, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcAlternator, 0, 35);
    lv_arc_set_value(ui_ArcAlternator, 17);
    lv_arc_set_bg_angles(ui_ArcAlternator, 190, 260);
    lv_obj_set_style_arc_color(ui_ArcAlternator, lv_color_hex(0x030032), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcAlternator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcAlternator, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcAlternator, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcSolar = lv_arc_create(ui_ScrMultiGauge);
    lv_obj_set_width(ui_ArcSolar, lv_pct(90));
    lv_obj_set_height(ui_ArcSolar, lv_pct(90));
    lv_obj_set_align(ui_ArcSolar, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcSolar, 0, 35);
    lv_arc_set_value(ui_ArcSolar, 17);
    lv_arc_set_bg_angles(ui_ArcSolar, 280, 350);
    lv_arc_set_mode(ui_ArcSolar, LV_ARC_MODE_REVERSE);
    lv_obj_set_style_arc_color(ui_ArcSolar, lv_color_hex(0x323200), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcSolar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcSolar, lv_color_hex(0xFFFF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcSolar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcSolar, lv_color_hex(0xFFFF00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcSolar, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcVerbrauch = lv_arc_create(ui_ScrMultiGauge);
    lv_obj_set_width(ui_ArcVerbrauch, lv_pct(90));
    lv_obj_set_height(ui_ArcVerbrauch, lv_pct(90));
    lv_obj_set_align(ui_ArcVerbrauch, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_ArcVerbrauch, 0, 35);
    lv_arc_set_value(ui_ArcVerbrauch, 17);
    lv_arc_set_bg_angles(ui_ArcVerbrauch, 30, 150);
    lv_obj_set_style_arc_color(ui_ArcVerbrauch, lv_color_hex(0x320000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcVerbrauch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcVerbrauch, lv_color_hex(0xBE0404), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcVerbrauch, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcVerbrauch, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcVerbrauch, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_KreisMG = lv_obj_create(ui_ScrMultiGauge);
    lv_obj_set_width(ui_KreisMG, lv_pct(40));
    lv_obj_set_height(ui_KreisMG, lv_pct(40));
    lv_obj_set_align(ui_KreisMG, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_KreisMG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_KreisMG, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KreisMG, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KreisMG, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_KreisMG, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_BtnTxt);
    ui_object_set_themeable_style_property(ui_KreisMG, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_BtnTxt);

    ui_LblMGVolt = lv_label_create(ui_KreisMG);
    lv_obj_set_width(ui_LblMGVolt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblMGVolt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblMGVolt, lv_pct(0));
    lv_obj_set_y(ui_LblMGVolt, lv_pct(-15));
    lv_obj_set_align(ui_LblMGVolt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblMGVolt, "13,5 V");
    ui_object_set_themeable_style_property(ui_LblMGVolt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_BtnTxt);
    ui_object_set_themeable_style_property(ui_LblMGVolt, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_BtnTxt);
    lv_obj_set_style_text_font(ui_LblMGVolt, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblMGAmp = lv_label_create(ui_KreisMG);
    lv_obj_set_width(ui_LblMGAmp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblMGAmp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblMGAmp, lv_pct(0));
    lv_obj_set_y(ui_LblMGAmp, lv_pct(25));
    lv_obj_set_align(ui_LblMGAmp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblMGAmp, "-2,45A");
    ui_object_set_themeable_style_property(ui_LblMGAmp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_BtnTxt);
    ui_object_set_themeable_style_property(ui_LblMGAmp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_BtnTxt);
    lv_obj_set_style_text_font(ui_LblMGAmp, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblMGArcLoad = lv_label_create(ui_ScrMultiGauge);
    lv_obj_set_width(ui_LblMGArcLoad, lv_pct(20));
    lv_obj_set_height(ui_LblMGArcLoad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblMGArcLoad, lv_pct(-35));
    lv_obj_set_y(ui_LblMGArcLoad, lv_pct(0));
    lv_obj_set_align(ui_LblMGArcLoad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblMGArcLoad, "+0,00 A");
    ui_object_set_themeable_style_property(ui_LblMGArcLoad, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_BtnTxt);
    ui_object_set_themeable_style_property(ui_LblMGArcLoad, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_BtnTxt);
    lv_obj_set_style_text_align(ui_LblMGArcLoad, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbLMGArcSolar = lv_label_create(ui_ScrMultiGauge);
    lv_obj_set_width(ui_LbLMGArcSolar, lv_pct(20));
    lv_obj_set_height(ui_LbLMGArcSolar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbLMGArcSolar, lv_pct(35));
    lv_obj_set_y(ui_LbLMGArcSolar, lv_pct(-1));
    lv_obj_set_align(ui_LbLMGArcSolar, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbLMGArcSolar, "+3,5 A");
    ui_object_set_themeable_style_property(ui_LbLMGArcSolar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_BtnTxt);
    ui_object_set_themeable_style_property(ui_LbLMGArcSolar, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_BtnTxt);
    lv_obj_set_style_text_align(ui_LbLMGArcSolar, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblMGArcVerbrauch = lv_label_create(ui_ScrMultiGauge);
    lv_obj_set_width(ui_LblMGArcVerbrauch, lv_pct(20));
    lv_obj_set_height(ui_LblMGArcVerbrauch, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblMGArcVerbrauch, lv_pct(11));
    lv_obj_set_y(ui_LblMGArcVerbrauch, lv_pct(30));
    lv_obj_set_align(ui_LblMGArcVerbrauch, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblMGArcVerbrauch, "0,5 A");
    ui_object_set_themeable_style_property(ui_LblMGArcVerbrauch, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_BtnTxt);
    ui_object_set_themeable_style_property(ui_LblMGArcVerbrauch, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_BtnTxt);

    ui_ImgVerbrauch = lv_img_create(ui_ScrMultiGauge);
    lv_img_set_src(ui_ImgVerbrauch, &ui_img_icon_fridge_50_png);
    lv_obj_set_width(ui_ImgVerbrauch, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_ImgVerbrauch, LV_SIZE_CONTENT);    /// 51
    lv_obj_set_x(ui_ImgVerbrauch, -28);
    lv_obj_set_y(ui_ImgVerbrauch, 106);
    lv_obj_set_align(ui_ImgVerbrauch, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgVerbrauch, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgVerbrauch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgSolar = lv_img_create(ui_ScrMultiGauge);
    lv_img_set_src(ui_ImgSolar, &ui_img_icon_solar_50_png);
    lv_obj_set_width(ui_ImgSolar, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_ImgSolar, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_x(ui_ImgSolar, 93);
    lv_obj_set_y(ui_ImgSolar, -69);
    lv_obj_set_align(ui_ImgSolar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgSolar, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgSolar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgLoad = lv_img_create(ui_ScrMultiGauge);
    lv_img_set_src(ui_ImgLoad, &ui_img_icon_piston_50_png);
    lv_obj_set_width(ui_ImgLoad, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_ImgLoad, LV_SIZE_CONTENT);    /// 53
    lv_obj_set_x(ui_ImgLoad, -78);
    lv_obj_set_y(ui_ImgLoad, -75);
    lv_obj_set_align(ui_ImgLoad, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgLoad, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgLoad, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblName = lv_label_create(ui_ScrMultiGauge);
    lv_obj_set_width(ui_LblName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblName, lv_pct(0));
    lv_obj_set_y(ui_LblName, lv_pct(-30));
    lv_obj_set_align(ui_LblName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblName, "JL-LiPo");
    ui_object_set_themeable_style_property(ui_LblName, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_BtnTxt);
    ui_object_set_themeable_style_property(ui_LblName, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_BtnTxt);
    lv_obj_set_style_text_font(ui_LblName, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScrMultiGauge, ui_event_ScrMultiGauge, LV_EVENT_ALL, NULL);

}

void ui_ScrMultiGauge_screen_destroy(void)
{
    if(ui_ScrMultiGauge) lv_obj_del(ui_ScrMultiGauge);

    // NULL screen variables
    ui_ScrMultiGauge = NULL;
    ui_ConMutiGauge = NULL;
    ui_ArcAlternator = NULL;
    ui_ArcSolar = NULL;
    ui_ArcVerbrauch = NULL;
    ui_KreisMG = NULL;
    ui_LblMGVolt = NULL;
    ui_LblMGAmp = NULL;
    ui_LblMGArcLoad = NULL;
    ui_LbLMGArcSolar = NULL;
    ui_LblMGArcVerbrauch = NULL;
    ui_ImgVerbrauch = NULL;
    ui_ImgSolar = NULL;
    ui_ImgLoad = NULL;
    ui_LblName = NULL;

}
